os:
  - linux

language: node_js

node_js:
  - node
  - '9'
  - '8'

cache:
  directories:
  - "$HOME/.npm"

before_install:
  - npm config set loglevel warn
  - npm install --global npm@latest

install:
  - npm ci || npm install

script:
  - npm run lint
  - npm run test
