os:
  - linux

language: node_js

node_js:
  - node
  - '8'

cache:
  directories:
    - '$HOME/.npm'

before_install:
  - npm config set loglevel warn
  - npm install --global npm@latest

install:
  - npm ci || npm install

script:
  - npm run lint
  - npm run test:ci
  - lerna run build

jobs:
  include:
    - stage: release
      if: branch = master
      node_js: '8'
      script: npm run semantic-release
