export default [
  {
    title: 'Components',
    to: '/components',
    submenu: [
      { title: 'App', to: '?package=app' },
      { title: 'AppBar', to: '?package=appBar' },
      { title: 'Action Page', to: '?package=action-page' },
      { title: 'Button', to: '?package=button' },
      { title: 'Collection', to: '?package=collection' },
      { title: 'Collection Group', to: '?package=collection-group' },
      { title: 'Collection Item', to: '?package=collection-item' },
      { title: 'Dialog', to: '?package=dialog' },
      { title: 'Full Page Loading', to: '?package=full-page-loading' },
      { title: 'Sprite', to: '?package=sprite' },
      { title: 'Icon', to: '?package=icon' },
      { title: 'Input', to: '?package=input' },
      { title: 'Row', to: '?package=row' },
      { title: 'Printable', to: '?package=printable' },
      { title: 'Progress', to: '?package=progress' },
      { title: 'Range', to: '?package=range' },
      { title: 'Switch', to: '?package=switch' },
      // { title: 'Deprecated', to: '/components/deprecated',
      //   submenu: [
      //     { title: 'Avatar', to: '/avatar', deprecated: true },
      //     { title: 'Grid', to: '/grid', deprecated: true },
      //     { title: 'Grid Item', to: '/grid-item', deprecated: true },
      //     { title: 'Image', to: '/image', deprecated: true },
      //     { title: 'Ink', to: '/ink', deprecated: true },
      //     { title: 'Input Container', to: '/input-container', deprecated: true },
      //     { title: 'Link', to: '/link', deprecated: true },
      //     { title: 'Loading Group', to: '/loading-group', deprecated: true },
      //     { title: 'Switcher', to: '/switcher', deprecated: true },
      //     { title: 'Switcher Item', to: '/switcher-item', deprecated: true },
      //     { title: 'Tab Item', to: '/tab-item', deprecated: true },
      //     { title: 'Tabs', to: '/tabs', deprecated: true },
      //   ],
      // },
    ],
  },
  // {
  //   title: 'Native API',
  //   to: '/native',
  //   submenu: [{ title: 'Quickstart', to: '/native/quickstart' }],
  // },
  // { title: 'Styles', to: '/styles' },
  // { title: 'Utils', to: '/utils' },
  // { title: 'Development',
  //   to: '/development',
  //   submenu: [
  //     { title: 'POS', to: '/pos' },
  //   ],
  // },
]
