export default [
  {
    title: 'Components',
    to: 'components',
  },
  // {
  //   title: 'Native API',
  //   to: '/native',
  //   submenu: [{ title: 'Quickstart', to: '/native/quickstart' }],
  // },
  // { title: 'Styles', to: '/styles' },
  // {
  //   title: 'Components',
  //   to: '/components',
  //   submenu: [
  //     { title: 'App', to: '/app' },
  //     { title: 'Action Page', to: '/action-page' },
  //     { title: 'Button', to: '/button' },
  //     { title: 'Collection', to: '/collection' },
  //     { title: 'Collection Group', to: '/collection-group' },
  //     { title: 'Collection Item', to: '/collection-item' },
  //     { title: 'Dialog', to: '/dialog' },
  //     { title: 'Full Page Loading', to: '/full-page-loading' },
  //     { title: 'Sprite', to: '/sprite' },
  //     { title: 'Icon', to: '/icon' },
  //     { title: 'Input', to: '/input' },
  //     { title: 'Row', to: '/row' },
  //     { title: 'AppBar', to: '/appBar' },
  //     { title: 'Printable', to: '/printable' },
  //     { title: 'Progress', to: '/progress' },
  //     { title: 'Range', to: '/range' },
  //     { title: 'Switch', to: '/switch' },
  //     { title: 'Deprecated', to: '/components/deprecated',
  //       submenu: [
  //         { title: 'Avatar', to: '/avatar', deprecated: true },
  //         { title: 'Grid', to: '/grid', deprecated: true },
  //         { title: 'Grid Item', to: '/grid-item', deprecated: true },
  //         { title: 'Image', to: '/image', deprecated: true },
  //         { title: 'Ink', to: '/ink', deprecated: true },
  //         { title: 'Input Container', to: '/input-container', deprecated: true },
  //         { title: 'Link', to: '/link', deprecated: true },
  //         { title: 'Loading Group', to: '/loading-group', deprecated: true },
  //         { title: 'Switcher', to: '/switcher', deprecated: true },
  //         { title: 'Switcher Item', to: '/switcher-item', deprecated: true },
  //         { title: 'Tab Item', to: '/tab-item', deprecated: true },
  //         { title: 'Tabs', to: '/tabs', deprecated: true },
  //       ],
  //     },
  //   ],
  // },
  // { title: 'Utils', to: '/utils' },
  // { title: 'Development',
  //   to: '/development',
  //   submenu: [
  //     { title: 'POS', to: '/pos' },
  //   ],
  // },
]
